export const INIT_LOCATIONS = 'INIT_LOCATIONS';
export const SELECT_LOCATION = 'SELECT_LOCATION';
export const DESELECT_LOCATION = 'DESELECT_LOCATION';
export const TOGGLE_LOCATION = 'TOGGLE_LOCATION';
export const SET_MAP_LOCATIONS = 'SET_MAP_LOCATIONS';

export const SELECT_MAP = 'SELECT_MAP';
