export const INIT_LOCATIONS = 'INIT_LOCATIONS';
export const SELECT_LOCATION = 'SELECT_LOCATION';
export const DESELECT_LOCATION = 'DESELECT_LOCATION';
export const TOGGLE_LOCATION = 'TOGGLE_LOCATION';
